id: A85538D36
title: Aspiration for the Land of Great Bliss
type: translation
pechas:
- IBC04B9CD
- ICA9C7609
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:33.225438
  last_modified_at: 2023-01-04 12:06:33.225447
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IBC04B9CD/F09B: 0082
  ICA9C7609/7496: 0082
